sample_method: 'frontier'
phases:
  - md: "subgraph"  # mode
    bs: 8000        # batch size
    lr: 0.05       # learning rate
    es: 0           # epoch start
    ee: 40       # epoch end
    load: 0         # load sampled subgraph from disk
    num_sub: 200    # number of subgraphs to load (use recursively)
    save: 0         # save sampled subgraph to disk
